# Configuración de la conexión a PostgreSQL
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=Labcom,2015
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/pweb

# Habilitar el uso de Hibernate ORM 
quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.http.root-path=/matriculaAPI/v1.1
quarkus.http.port=8081
quarkus.http.cors=true
quarkus.http.cors.origins=*